require("myconf.core.editor.options").setup()
require("myconf.core.ui.tabline").setup()
require("myconf.core.mappings").setup()
require("myconf.core.cmd").setup()
require("myconf.core.events").setup()
